<?php

namespace App\Models;

use App\Models\Concerns\BelongsToBranch;
use Database\Factories\IncomeFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Income ledger entry. Task 10.3 writes the system-generated fee income
 * (one per settled payment, payment_id set → immutable); Task 11.2 adds the
 * manual CRUD. Branch is stamped/scoped automatically via BelongsToBranch.
 * A row with payment_id set is system-generated and cannot be edited/deleted.
 */
#[Fillable([
    'branch_id', 'category_id', 'payment_id', 'title',
    'amount', 'date', 'description', 'created_by',
])]
class Income extends Model
{
    /** @use HasFactory<IncomeFactory> */
    use BelongsToBranch, HasFactory;

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'date' => 'date',
        ];
    }

    /**
     * Whether this income was system-generated by a fee payment and is
     * therefore immutable.
     */
    public function isSystem(): bool
    {
        return $this->payment_id !== null;
    }

    /**
     * The payment that generated this income, when system-generated.
     */
    public function payment(): BelongsTo
    {
        return $this->belongsTo(Payment::class);
    }

    /**
     * The category this income is grouped under, when set.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}
